"""Preview-only help text, mapped to the Tk UI; no backend imports or calls."""

HELP_TEXT = {
    "profile": ("存档信息", "存档只用于填写工具参数，不会读取、写入或删除游戏存档。当前预览仅支持手动输入；真实档案选择与管理尚未接入。"),
    "profile_fields": ("存档字段", "火红 / 叶绿没有时钟电池参数；主机用于选择对应的 NX Seed 表。当前预览的游戏版本与野生、孵蛋页同步；语言与 TID 页同步，从存档窗口修改语言不会重置已填的目标或延迟。"),
    "sid_scope": ("SID 反查范围", "支持第三世代 Method 1/2/4。闪光公式只能确定 8 个真实 SID 候选；建档链前 10000 ADV 有命中时再选最早值。反查服务尚未接入此预览。"),
    "sid_party": ("队伍输入规则", "只处理队伍前 N 位，按实际顺序填写中文名、英文名或全国图鉴编号、初始等级、来源和六项努力值 EV。野生来源需填写 Ten Lines 相遇地点；不支持孵蛋来源与非 Method 1/2/4 个体。"),
    "sid_ack": ("队伍与糖果准备", "确认队伍顺序、宝可梦、初始等级、来源和六项 EV 均准确；神奇糖果位于背包第一页第一格。糖果数是每只最多使用数量。"),
    "direct": ("指定 Seed / 帧数", "指定模式跳过筛选搜索，直接采用已有初始 Seed 和目标消耗帧；Seed 模式必须手动选择，并与游戏设置一致。此预览不搜索或校验方案。"),
    "capture": ("出闪后处理", "正式脚本未勾选自动抓捕时，会在识别到闪光后停止，交给用户处理。麻痹与点到为止用于自动抓捕过程。"),
    "item": ("道具乱数模式", "仅野生目标可用，与 SID 遍历互斥。物种正确且“无道具”标签不匹配时计为一次命中；按队伍空位保存相应次数的携带道具目标，支持 1–5 个空位。"),
    "traversal": ("SID 遍历模式", "仅野生目标可用。正式生成前确认当前 TID，并询问是否给劲敌取名：未取名从奇数 ADV 1901 开始，取名从偶数 ADV 1900 开始，每次 +2。每个 SID 先搜索低帧闪光目标；明确未出闪才推进并保存下一起点，中途停止保留当前候选。断点与运行服务尚未接入此预览。"),
    "traversal_start": ("自定义 SID 起点", "仅高级模式且开启野生 SID 遍历时可编辑。留空沿用 1901（劲敌未取名）或 1900（已取名）；自定义值须匹配路线奇偶，并使用独立断点，不覆盖其他起点的进度。"),
    "iv": ("个体值范围与预设", "上方为最低值，下方为最高值。6V 为六项精确 31；0A、0S、0A0S 将对应攻击 / 速度设为精确 0，其余项精确 31。不限为六项 0–31；点击能力名称可单独重置。"),
    "egg_seed": ("孵蛋 Seed 模式", "必须与 Ten Lines Egg 页搜索时使用的游戏设置一致；不能保留“请选择”。"),
    "egg_start": ("从 254 步基础档开始", "“从已完成 254 步准备开始”要求当前存档已经完成并保存 254 步准备，只跳过一次性准备，仍执行所选 Seed 启动方案与全部校准流程。"),
    "egg_target": ("目标数据来源", "先从 Ten Lines Egg 页取得同一个初始 Seed 下的 Held / 生成帧和 Pickup / 领取帧；Pickup 至少晚 1800 ADV。亲本 A / B 性别与六项 IV、双亲相性须与搜索输入一致。"),
    "egg_ack": ("孵蛋运行确认", "启动前确认 254 步基础档、队伍空位、甜甜香气宝可梦与 Ten Lines 目标参数。该流程尚未完成本机整轮实机验收。确认不持久化，载入配置后需要重新勾选；预览不启动流程。"),
    "egg_config": ("亲本与全部配置", "亲本配置只包含双亲资料；全部配置另包含运行条件与目标参数。两种配置作用域不同，均不保存当次运行确认；本预览的保存与载入服务尚未接入。"),
    "tid_sid": ("SID 处理", "目标 SID 模式自动计算最低可用 ADV，搜索上限为 1,000,000 ADV；不乱数 SID 模式固定 F3，由实际生成链决定 SID。连续御三家流程在后一模式取得实际 SID 后动态生成目标。"),
    "tid_detect": ("固定延迟检测", "正式流程先测量 OP、F1、F2、F3 和实际 OP 修正；完整后自动回填、重新生成并预检计划，通过后继续运行。本预览未接入检测、回填与运行。"),
    "tid_pid": ("6V 闪 PID 与 SID", "普通模式固定 PID 7942EF72，高级模式可编辑。按当前 TID 与 PID 计算闪光 PSV；搜索起点计入 F3 固定延迟、语言脚本的 SID 前置补偿和 SID ADV 修正，在 1,000,000 ADV 内选最早可执行的 SID，并非数值最小的 SID。计算仅回填目标 SID，不启动游戏；此预览尚未接入计算。"),
    "tid_frames": ("帧数单位", "OP / F1 / F2 的帧数为 RNG advance，沿用 TID 脚本的 120.00144 advance/s 换算；WAIT、固定延迟与 OP 修正使用毫秒。中心与半径用于乱数搜索，起点与最大范围用于穷举。"),
    "tid_targets": ("多个目标", "主目标始终保留；额外目标用空格或逗号分隔，最多 31 个，例如 00000, 33333, 65535。仅穷举使用；自动转乱数后锁定已确认的区域目标。"),
    "tid_near": ("目标区间确认", "在同一参数的去噪窗口内，对每个目标分别统计环形距离内的结果。允许不同 TID，默认 ±100 内 3 次；跨参数不累加。达到次数立即转乱数，窗口满仍未达到则继续穷举。距离不是帧补偿；预览不执行判断或自动切换。"),
    "tid_auto_radius": ("自动切换后半径", "转乱数后采用 OP / F1 / F2 半径。正式执行时，超出可执行下限会自动缩小；负数归零，按原搜索步长 2 向下取偶数。预览只保存输入，不执行半径计算。"),
    "tid_delay": ("固定延迟编辑", "默认不允许手动编辑 OP / F1 / F2 / F3；勾选后可在本窗口输入。正式版固定延迟检查完成后会自动回填，此预览尚未接入检查。"),
    "starter": ("连续御三家流程", "TID → 球前存档 → 御三家。游戏版本沿用 TID / SID 基本条件；穷举模式使用实际 TID 与 SID ADV。御三家阶段的 Sound、Button Mode、Seed Button 独立于 TID 阶段；校准固定方案 0。"),
    "starter_settings": ("御三家游戏设置", "这些设置独立于上方 TID 阶段的 Sound、Button Mode 和 Seed Button；游戏版本沿用 TID / SID 基本条件。"),
    "tid_any": ("任意 TID 接续", "仅连续御三家 + 穷举模式可用。开启后忽略目标 TID 与特殊号码条件，首次满足完整性要求的 TID 可接续御三家流程。"),
    "tid_denoise": ("任意 TID 去噪", "默认开启。关闭后，首个完整识别且数值合法的 TID 可直接接续；缺位或非法识别仍不会放行。仅在任意 TID 接续开启时适用。"),
    "tid_resume": ("搜索续跑", "正式版默认开启，参数自动保存；取消后从所填起点开始。续跑重试停止时的当前点并重新去噪，已命中完成的进度不会继续；打开工具不会自动运行游戏。本预览未接入参数保存和断点读取。"),
    "records": ("TID 实测表", "正式版自动记录有效 TID，同游戏、机型与参数分别统计；不记录 SID、SID ADV 或 F3。出现次数表示观测次数，不保证再次命中。表内最多 1000 项，CSV 导出包含全部筛选结果；预览未读取数据库。"),
    "script": ("高级脚本测试", "原地执行所选 ECS，不经过方案搜索、参数替换或 main.ecs 生成。兼容运行器对应正式工具，原始 EasyCon 1.6.4-a CLI 用于同脚本 A/B 对照；同目录 lib 与 ImgLabel 会被使用。测试前必须核对脚本内容、游戏位置和存档状态。预检与运行尚未接入。"),
    "source": ("2.0 自动乱数脚本包路径", "野生 / 静态、孵蛋和脚本测试的正式版 / 时间轴版入口从此目录读取。SID 与 TID 保留各自的独立脚本路径，修改这里不替代它们。路径选择与校验尚未接入。"),
    "sid_source": ("SID 独立脚本路径", "SID 查找使用独立的 2.0 脚本包目录，不与野生 / 静态、孵蛋的公共脚本包路径混用。路径选择与校验尚未接入。"),
    "tid_source": ("TID 独立脚本路径", "TID 建档阶段使用独立的 1.3.7 脚本包目录；接续御三家阶段使用公共 2.0 脚本包。路径选择与校验尚未接入。"),
    "vpad": ("虚拟手柄与状态浮窗", "正式版连接当前串口并打开键盘虚拟手柄及 100×100 置顶状态浮窗。绿色表示正在发送的按键；左键唤出控制窗口，右键拖动，中键隐藏。自动脚本运行时不可开启，以免串口冲突。此预览未接入设备。"),
    "advanced": ("高级模式", "开放 Seed 校准 / 启动、脚本入口、反查扩窗、奇偶调整、TID 闪 PID 与野生 SID 遍历起点，并显示脚本测试页。入口和扩窗在旁边的“高级设置”中。正式版只把指纹不一致降为警告；文件缺失、语法和参数错误仍阻止运行。预览不执行检查。"),
    "adaptive": ("HOME_BUFFER 稳定低分自适应", "作用于 2.0、TID 和 SID，默认关闭；只有同一状态连续稳定命中时才采用低于 95 的分数，只接受稳定的唯一最高分，不影响其他 OCR。预览仅保留开关状态。"),
    "entry": ("2.0 脚本入口", "正式版对应 NS火叶全自动一键乱数2.0.ecs，时间轴版对应 NS火叶全自动一键乱数2.0-时间轴.ecs。自选 ECS 仅在脚本测试页提供；关闭高级模式恢复正式入口。预览尚未接入路径解析。"),
    "seed_advanced": ("Seed 高级方案", "高级模式可修改。关闭后，野生 / 静态校准恢复方案 0，孵蛋恢复方案 2，Seed 启动恢复方案 0。御三家实际请求始终固定校准方案 0。"),
    "output_log": ("脚本输出日志", "精简日志保留状态、误差、修正和命中；完整调试日志增加识图分数、候选和校准细节。只控制生成的 2.0 脚本（含孵蛋与御三家），不改变时序，也不等同于脚本测试页的 EasyCon 详细日志。"),
    "reverse": ("反查扩窗与奇偶调整", "反查无结果时按层扩窗；每层填写相对目标中心的绝对 Seed 容差与消耗帧半宽，不是逐层累加。0 层关闭，窗口越大耗时越长。孵蛋预校准同样使用扩窗，但奇偶固定菜单方案。模板默认值尚未读取，留空不代表 0。"),
    "precalibration": ("命中后更新预校准", "默认关闭，完整命中后保存 Seed 与可用帧修正，按游戏、机型、Seed 模式、启动、正式 / 时间轴入口和流程隔离。正式版普通定点只复用 Seed；时间轴定点、野生、孵蛋与御三家可复用帧修正，TID / SID 阶段不参与。预览不保存记录。"),
    "labels": ("设备标签覆盖与导入", "正式版按采集设备名称独立保存覆盖，只应用到生成工程，不修改原始标签包；可导入多个 .IL 文件或文件夹。此预览未接入导入、拖放、诊断或设备覆盖。"),
    "update": ("整包程序更新", "正式绿色版每天最多自动检查一次稳定版，发现新版会先询问，再下载并校验 ZIP 大小与 SHA-256，退出后交换目录，失败恢复旧版；用户配置和日志不被替换。源码模式不使用自更新，此预览不检查更新。"),
}

CARD_HELP = {
    "存档信息": "profile", "SID 查找条件": "sid_scope", "队伍闪光宝可梦": "sid_party",
    "个体值筛选": "iv", "搜索范围": "direct", "更多筛选与出闪后处理": "traversal",
    "孵蛋运行条件": "egg_start", "孵蛋目标": "egg_target", "TID / SID 基本条件": "tid_sid",
    "乱数中心 / 穷举范围": "tid_frames", "游戏设置与固定延迟": "tid_delay",
    "御三家连续乱数": "starter", "参数保存与穷举续跑": "tid_resume", "TID 实测表": "records",
    "直接运行 ECS 测试脚本": "script", "EasyCon 1.6.4-a 与设备": "source",
    "SID 查找脚本": "sid_source", "TID 1.3.7 脚本包": "tid_source",
    "脚本日志设置": "output_log", "脚本入口": "entry", "高级反查设置": "reverse",
    "设备标签诊断与覆盖": "labels",
}

FIELD_HELP = {
    "profile_game": "profile_fields", "profile_language": "profile_fields",
    "wild_tid": "profile", "wild_sid": "profile", "sid_count": "sid_party", "sid_candies": "sid_ack",
    "wild_search_mode": "direct", "wild_seed_mode": "direct", "wild_direct_seed": "direct", "wild_direct_adv": "direct",
    "wild_slots": "item", "wild_traversal_max": "traversal", "wild_traversal_start": "traversal_start",
    "egg_seed_mode": "egg_seed", "egg_start": "egg_start", "egg_seed": "egg_target", "egg_held": "egg_target", "egg_pickup": "egg_target",
    "tid_sid_mode": "tid_sid", "tid_sid": "tid_sid", "tid_pid": "tid_pid",
    "tid_additional_targets": "tid_targets", "tid_near_distance": "tid_near", "tid_near_hits": "tid_near",
    "starter_sound": "starter_settings", "starter_button": "starter_settings", "starter_seed_button": "starter_settings",
    "script_path": "script", "script_backend": "script", "script_entry": "entry",
    "source": "source", "sid_source": "sid_source", "tid_source": "tid_source", "output_log": "output_log",
    "parity": "reverse", "layers": "reverse",
    **{f"expansion_{i}_{axis}": "reverse" for i in range(1, 4) for axis in ("seed", "adv")},
    **{f"tid_{axis}_{part}": "tid_frames" for axis in ("op", "f1", "f2") for part in ("target", "radius", "start", "range")},
    **{f"tid_{axis}_delay": "tid_delay" for axis in ("op", "f1", "f2", "f3")},
    **{f"tid_auto_{axis}_range": "tid_auto_radius" for axis in ("op", "f1", "f2")},
}

ACTION_HELP = {
    "6V 闪 SID": "tid_pid", "虚拟手柄": "vpad", "检查程序更新": "update",
    "保存亲本配置": "egg_config", "载入亲本配置": "egg_config", "保存全部配置": "egg_config", "载入全部配置": "egg_config",
    "选择标签文件（可多选）": "labels", "选择标签文件夹": "labels", "清除当前设备覆盖": "labels",
}
